name: Renovate Self-Hosted

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "org-inherited-config.json"
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs:
      log-level:
        description: "Set the Renovate log level (default: info)"
        required: false
        default: info
        type: choice
        options:
          - info
          - debug

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          token: ${{ steps.get-token.outputs.token }}
          persist-credentials: false

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@0b17c4eb901eca44d018fb25744a50a74b2042df # v46.1.4
        env:
          RENOVATE_DRY_RUN: ${{ github.event_name == 'pull_request' && 'full' }}
          LOG_LEVEL: ${{ github.event.inputs.log-level || 'info' }}
        with:
          token: ${{ steps.get-token.outputs.token }}
          configurationFile: ./renovate-config.json
